LEXICON_ENG = {
    "ling": "🇬🇧English language selected",
    "sub": "🔗Subscribe",
    "sub_ready": "✅I subscribed",
    "sub_no": "❌Subscription not detected! To continue, please subscribe",
    "menu": "🤖Welcome to the main menu!\n🧑‍💻Here you can familiarize yourself with the commands that will be useful for working with me!\n\n\n/start – restart bot✅\n/premium – buy premium💎\n/tokens – buy tokens💳\n/profile – view profile👤\n/neuroseti – list of available neural networks👾\n/help – contact administration🔗\n/language – choose language🗣",
    "premium": "Subscription to ChatGPT | Neural Networks for only 499rub\n\nSubscription features:\n\n✅Generation of full-fledged Coursework, Thesis, Essays, Abstracts\n✅Unlimited number of requests for ChatGPT4 omni\n✅Tokens are consumed twice slower\n✅Buy tokens at cost price\n✅Use the bot without restrictions\n✅Priority in the request queue\n✅Communicating with the bot by voice messages\n✅Working without ADVERTISING\n✅Additional 500 tokens\n\nIf you have any problems with balance replenishment - write to technical support: @Kseny_7",
    "buy": "💰Pay subscription",
    "check_pay": "👀Check payment",
    "back": "◀️Back",
    "pay_yes": "🟢Payment was successful, now all PREMIUM features are available to you!",
    "pay_tokens_yes": "🟢Payment was successful, tokens are credited to your balance!",
    "pay_no": "🔴Payment not detected, please try again!",
    "profile_kb": "👤Profile",
    "neuros_kb": "👾AI",
    "premium_kb": "💎Premium",
    "service_kb": "📋Services",
    "tokens": "⚡️Tokens",
    "help": "💬Help",
    "support": "🤝Support",
    "10k": "10.000 – 99 rub",
    "20k": "🔥20.000 – 199 rub",
    "30k": "30.000 – 299 rub",
    "150k": "150.000 – 999 rub",
    "500k": "500.000 – 2699 rub",
    "10k_prem": "10.000 – 49 rub",
    "20k_prem": "🔥20.000 – 99 rub",
    "30k_prem": "30.000 – 159 rub",
    "150k_prem": "150.000 – 459 rub",
    "500k_prem": "500.000 – 1399 rub",
    "no_mode": "❌No task",
    "Essay": "📝Essay",
    "Coursework": "📖Coursework",
    "Seo": "💻Seo article"
}