LEXICON_ES = {
    "ling": "🇪🇸Ha elegido el español",
    "sub": "🔗Suscribirse",
    "sub_ready": "✅Me he suscrito",
    "sub_no": "❌No se ha detectado la suscripción. Para continuar, suscríbase",
    "menu": "🤖¡Bienvenido al menú principal!\n🧑‍💻¡Aquí puedes familiarizarte con los comandos que necesitarás para trabajar conmigo!\n\n\n/start – reiniciar el bot✅\n/premium – comprar premium💎\n/tokens – comprar tokens💳\n/profile – ver perfil👤\n/neuroseti – lista de redes neuronales disponibles👾\n/help – contactar con la administración🔗\n/language – seleccionar idioma🗣",
    "premium": "ChatGPT | Suscripción a Redes Neuronales por sólo 499rub\n\nCaracterísticas de la suscripción:\n\n✅Generación de trabajos de curso, disertaciones, ensayos y trabajos completos\n✅Número ilimitado de solicitudes de ChatGPT4 omni\n✅Los tokens se consumen el doble de lentamente\n✅Compra fichas a precio de coste\n✅Uso ilimitado de bots\n✅Prioridad en la cola de solicitudes\n✅Comunicación con el bot mediante mensajes de voz\n✅Trabajar sin PUBLICIDAD\n✅500 fichas adicionales\n\nSi tienes problemas con la reposición de saldo – escribe al soporte técnico: @Kseny_7",
    "buy": "💰Pagar suscripción",
    "check_pay": "👀Comprobar pago",
    "back": "◀️Volver",
    "pay_yes": "🟢El pago se ha realizado correctamente, ¡ya tienes disponibles todas las funciones PREMIUM!",
    "pay_tokens_yes": "🟢El pago se ha realizado correctamente, las fichas se han ingresado en su saldo!",
    "pay_no": "🔴¡Pago no detectado, por favor inténtelo de nuevo!",
    "profile_kb": "👤Profile",
    "neuros_kb": "👾AI",
    "premium_kb": "💎Premium",
    "tokens": "⚡️Tokens",
    "help": "💬Ayuda",
    "support": "🤝Soporte",
    "service_kb": "📋Servicios",
    "10k": "10.000 – 99 rub",
    "20k": "🔥20.000 – 199 rub",
    "30k": "30.000 – 299 rub",
    "150k": "150.000 – 999 rub",
    "500k": "500.000 – 2699 rub",
    "10k_prem": "10.000 – 49 rub",
    "20k_prem": "🔥20.000 – 99 rub",
    "30k_prem": "30.000 – 159 rub",
    "150k_prem": "150.000 – 459 rub",
    "500k_prem": "500.000 – 1399 rub",
    "no_mode": "❌Ninguna tarea",
    "Essay": "📝Ensayo",
    "Coursework": "📖Trabajo de curso",
    "Seo": "💻Artículo Seo"
}